---
- name: Configure Development Environment
  hosts: localhost
  become: false
  tasks:
    - name: Ensure ~/.profile exists and sources ~/.config/.profile
      ansible.builtin.lineinfile:
        dest: ~/.profile
        line: "[ -f ~/.config/.profile ] && source ~/.config/.profile"
        mode: "0644"
        create: true

    - name: Ensure ~/.bashrc exists and sources ~/.config/.bashrc
      ansible.builtin.lineinfile:
        dest: ~/.bashrc
        line: "[ -f ~/.config/.bashrc ] && source ~/.config/.bashrc"
        mode: "0644"
        create: true

    - name: Ensure ~/.config/.zshrc exists and sources ~/.config/.bashrc
      ansible.builtin.copy:
        dest: ~/.config/.zshrc
        content: |
          source ~/.config/.bashrc
        mode: "0644"
        force: false

    - name: Ensure ~/.zshrc exists and sources ~/.config/.zshrc
      ansible.builtin.lineinfile:
        dest: ~/.zshrc
        line: "[ -f ~/.config/.zshrc ] && source ~/.config/.zshrc"
        mode: "0644"
        create: true

    - include_tasks: tasks/ssh-config.yml

    - include_tasks: tasks/main.yml

    - include_tasks: tasks/git-config.yml

    - name: Check if .config/.git exists
      ansible.builtin.stat:
        path: ~/.config/.git
      register: git_stat

    - name: Clone Neovim config repository with SSH (skipped if .config/.git exists)
      ansible.builtin.git:
        repo: "git@github.com:SimHoZebs/.config.git"
        dest: ~/.config
        version: master
        update: true
        force: false
      when: not git_stat.stat.exists
