---
- name: Install essential packages
  apt:
    name:
      - curl
      - git
      - zsh
      - btop
      - wget
      - gcc
      - cmake
      - fzf
      - unzip
      - rsync
      - ripgrep
      - luarocks
      - python3-pip
    state: present
    update_cache: yes
  become: yes

- name: Check if Homebrew is installed
  ansible.builtin.command:
    cmd: brew --version
  register: brew_check
  ignore_errors: yes
  changed_when: false

- name: Install Homebrew
  ansible.builtin.shell:
    cmd: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  when: brew_check.rc != 0

- name: source .bashrc (for Homebrew)
  ansible.builtin.shell: source ~/.bashrc
  args:
    executable: /bin/bash

- name: Check if Go is installed
  ansible.builtin.command:
    cmd: go version
  register: go_check
  ignore_errors: yes
  changed_when: false

- name: Download Go archive
  get_url:
    url: https://go.dev/dl/go1.24.0.linux-amd64.tar.gz
    dest: /tmp/go1.24.0.linux-amd64.tar.gz
  when: go_check.rc != 0

- name: Extract Go archive
  become: yes
  ansible.builtin.unarchive:
    src: /tmp/go1.24.0.linux-amd64.tar.gz
    dest: /usr/local
    remote_src: yes
  when: go_check.rc != 0

- name: Ensure Go binary path is in system-wide profile
  become: yes
  lineinfile:
    path: /etc/profile
    line: "export PATH=$PATH:/usr/local/go/bin"
    create: yes

- name: Apply profile changes (for Go)
  shell: source /etc/profile
  args:
    executable: /bin/bash

- name: Check if rustup is installed
  ansible.builtin.command:
    cmd: rustup --version
  register: rustup_check
  ignore_errors: yes
  changed_when: false

- name: Install rustup
  ansible.builtin.shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  args:
    executable: /bin/bash
  when: rustup_check.rc != 0

- name: source .bashrc (for cargo)
  ansible.builtin.shell: source ~/.bashrc
  args:
    executable: /bin/bash

- name: Install tiktoken_core via luarocks
  ansible.builtin.shell: |
    . "~/.cargo/env"
    luarocks install tiktoken_core --local
  args:
    executable: /bin/bash

- name: Homebrew tap
  ansible.builtin.homebrew_tap:
    name:
      - arl/arl
  when: brew_check.rc == 0 or brew_check.failed is defined

- name: Install packages with Homebrew
  ansible.builtin.homebrew:
    name:
      - fzf
      - lazygit
      - neovim
      - zoxide
      - tmux
      - arl/arl/gitmux
      - nodejs
      - fd
      - gh
    state: present
  when: brew_check.rc == 0 or brew_check.failed is defined

- name: Clone TPM (Tmux Plugin Manager)
  ansible.builtin.git:
    repo: "https://github.com/tmux-plugins/tpm"
    dest: "~/.config/tmux/plugins/tpm"
    update: yes
