---
- name: Ensure Go bin directory is in PATH
  ansible.builtin.lineinfile:
    path: ~/.config/.bashrc
    line: 'export PATH="$HOME/go/bin:$PATH"'
    regexp: '^\s*export PATH=.*\$HOME/go/bin'
    state: present
