---
- name: Set up tmux plugins
  import_tasks: tmux.yml

- name: Set up Go PATH
  import_tasks: go.yml

- name: Install gitmux
  import_tasks: gitmux.yml

- name: Install pnpm
  import_tasks: pnpm.yml
