---
- name: Check if zoxide is installed
  ansible.builtin.command: zoxide --version
  register: zoxide_check
  failed_when: false
  changed_when: false

- name: Install zoxide
  ansible.builtin.shell: |
    curl -sSfL https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | sh
  args:
    executable: /bin/bash
  when: zoxide_check.rc != 0
